### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1111]
- Lot of python dependencies seems outdated'
Please check https://requires.io/github/Cloud-CV/EvalAI/requirements/?branch=master

**Comment by deshraj** [comment]
@aayusharora, thanks for opening this issue. 👍

**Comment by deshraj** [comment]
If anyone is willing to work on this issue, please take care of the following features:

1. Make sure that nothing is breaking after updating the package
2. Look for the improvements that have been done in the library so that things don't get mess up once merged
3. Please provide the link to the library's latest version and list the latest features added to that version

**Comment by the-dagger** [comment]
@deshraj I would like to work on this issue, could you please assign me to it?

**Comment by aayusharora** [comment]
@the-dagger Please go ahead.

**Comment by isht3** [comment]
@the-dagger Can I take over? :smile:

**Comment by the-dagger** [comment]
@isht3 I've fixed this in #1136 already.
Maybe @deshraj can review it :)

**Comment by deshraj** [comment]
Closing this since we decided to move with the existing version of packages.
