### ISSUE TITLE
Add automatic reloading of rabbitmq worker from django admin.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1128]

**Comment by anuj-rathore** [comment]
@RishabhJain2018  If its unresolved, can I take this issue?

**Comment by isht3** [comment]
@RishabhJain2018 Is this available for taking up?

**Comment by RishabhJain2018** [comment]
@isht3 No, since we are now planning to shift to AWS SQS instead of RabbitMQ. Thanks for pointing it. I am closing it for now.

**Comment by isht3** [comment]
@RishabhJain2018 So the whole submission_worker have to be renewed yes?

**Comment by deshraj** [comment]
@isht3: yeah, the submission worker will undergo certain changes where we will remove the RabbitMQ part and use SQS instead. Also, one important thing to notice here is that since SQS cannot run on local machine for testing, so we would have to use some kind of mock messaging service. (There are plenty of them on Github)

**Comment by isht3** [comment]
So, I guess it will need a common script, development script and a production script in a structure like the settings is done now? The mock messaging service would go in the development script, yes? If it's needed, I can work on the setting up the mock server and testing using something like https://code.google.com/archive/p/mock/
