### ISSUE TITLE
Splitting the tests with too many lines to smaller test files (150 lines per file).

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/EvalAI#1234]
Hi, I was in the process for adding some tests when I noticed the `challenges/test_views.py` was over 2000 lines in a single file. Is there any improvements to performance? Could it be better if it was smaller chunks of code?

**Comment by deshraj** [comment]
@isht3: the way you can improve is the code quality. You might want to use inheritance in the tests to decrease the number of lines but this is not on the top priority so I would recommend you building new features instead of working on this. Please close this if you are not planning to work on this. :)

**Comment by isht3** [comment]
@deshraj Okay, thanks for the heads up!
