### ISSUE TITLE
Challenge List page should not require login

### ISSUE THREAD

**Issue by dhruvbatra** [Cloud-CV/EvalAI#1247]
What the title says. 

Just like the VQA challenge details are not being auth-wall, everything else should be visible as well.

**Comment by xamfy** [comment]
Can I take this?

**Comment by deshraj** [comment]
@xamfy: Yeah go ahead. 

Before you start working on this, the deliverable of this issue is:

[] Show the list of all the challenges whether the user is logged in or not. The UI can be similar to what we have on the dashboard for listing all the challenges.

Please let me know if something is unclear.

**Comment by xamfy** [comment]
@deshraj I've done the following things as of now:
1. Create a new route for all challenges
2. Create a new controller for that
3. New template for displaying the list of challenges

**Comment by anuj-rathore** [comment]
If the issue is still unresolved, can I can take this issue?
