### ISSUE TITLE
Methods of model redundant implemented

### ISSUE THREAD

**Issue by Marlysson** [Cloud-CV/EvalAI#1280]
In some models there are the method : ```get_attribute_model``` to get the your value, but your implementation don't there are nothing different , just a return.

There are some reason to this are implemented? And no a ```property``` ( if necessary )

**Comment by RishabhJain2018** [comment]
@Marlysson Can you please explain the issue. I didn't get your point.

**Comment by Marlysson** [comment]
Sure.
I was analysing the EvalAI code searching something to contribute and I saw this, by example:

https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L67-L73

A ```get_*``` method just return the same value from model's django, then I asked because this method if haven't any implementation into them.

**Comment by deshraj** [comment]
@Marlysson I get your point of what you are trying to say. Those methods are implemented intentionally since we want to use these methods in the future to show the start and end date time in a different way than what it is being shown now. 

Please feel free to take any other issues if you are interested in contributing to EvalAI. :)
