### ISSUE TITLE
Modify database seeding method

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1492]
## Deliverables

- [ ] Modify the seed command to accept an argument `-nc` which denotes the number of challenges that a developer wants to create for testing.
- [ ] Modify the seed script in such a way that it can be run multiple times (right now, if you run it once and then you try to run it again, then it throws an error).

**Comment by Obtin** [comment]
@deshraj I would like to proceed on this issue. Thank you

**Comment by deshraj** [comment]
@Obtin: sure, go ahead. :)

**Comment by isht3** [comment]
@Obtin Are you working on this?

**Comment by Obtin** [comment]
@isht3 yes :-)

**Comment by anweshknayak** [comment]
@Obtin I see you are working in #1373. Please take one issue at a time. 😃 So that others can work too.

**Comment by Obtin** [comment]
Done with #1373 , Starting working n this. Thank you.

**Comment by Obtin** [comment]
@deshraj I made changes in apps/base/management/commands/seed.py
'    def add_arguments(self, parser):
        parser.add_argument(
            '--nc', dest='nc', nargs='?', default=3,
            help = 'no.of challenges',
        )
'
`    def handle(self, *args, **options):
        self.nc = options['nc']
        self.stdout.write(self.style.SUCCESS('Starting the database seeder. Hang on...'))
        call_command('runscript', 'seed', '--settings', 'settings.dev')
        self.stdout.write(self.style.SUCCESS('Database successfully seeded.'))
`
the ouput is as follows: 
![modify](https://user-images.githubusercontent.com/25207205/36258480-cc6a93ae-1280-11e8-8bdb-d474a3834c10.png)
Further Plan: The 'nc' variable will be passed as an argument in scripts/seed.py file .
 
I am getting an error

> Exception while running run() in 'scripts.seed'
I guess it is due to the problem in `def run ` function.
Please let me know whether its right or I should continue with any other approach.

**Comment by Obtin** [comment]
@deshraj please have a look at it.

**Comment by isht3** [comment]
Hi @Obtin is the seeding exception issue resolved? :smile:

**Comment by Obtin** [comment]
@isht3 working on it will update you soon. :-)

**Comment by isht3** [comment]
@Obtin Okay, cool. I can work on the seeding exception if you have other issues to work on. :smile:

**Comment by Obtin** [comment]
@isht3 yeah sure, feel free to work on it.  :-)

**Comment by deshraj** [comment]
@isht3 if you are working on this, please complete it asap.

**Comment by isht3** [comment]
@deshraj I'll finish this right now.
