### ISSUE TITLE
Featured challenge on home page

### ISSUE THREAD

**Issue by viditjain08** [Cloud-CV/EvalAI#1508]
## Deliverables

- [ ] On the home page, the featured challenge is not selected on the basis of featured flag, but on the basis of approved_by_admin and published flag.

**Comment by aka-jain** [comment]
@deshraj please correct this if this is not intentional.

**Comment by deshraj** [comment]
@viditjain08: Good catch. Please feel free to work on it. Assigning this to you.

**Comment by deshraj** [comment]
Since @viditjain08 cannot work on this issue, so this is open now for anyone willing to take. You will have to work on top of #1512. There aren't lot of changes to be done in this feature.

**Comment by deshraj** [comment]
This issue is still unassigned. Please feel free to take this if someone is interested.

**Comment by JaneLiuUSA** [comment]
@deshraj I can work on it.

**Comment by RishabhJain2018** [comment]
Sure! you can. Please feel free to ask if you have doubts.

**Comment by JaneLiuUSA** [comment]
Hey I got error when I tried to push my code up to my branch. Is there any steps that I am missing?
```
$git push --set-upstream origin feature-challenge
remote: Permission to Cloud-CV/EvalAI.git denied to JaneLiuUSA.
fatal: unable to access 'https://github.com/Cloud-CV/EvalAI.git/': The requested URL returned error: 403
```

**Comment by RishabhJain2018** [comment]
Hi @JaneLiuUSA. Thanks for fixing the issue.
You can't push directly to CloudCV EvalAI repository since you are not a member of the organization.
Ideally, the flow should be:
1. Fork the EvalAI repository into your account.
2. Create a new branch and then make the required changes in the code.
3. Open a PR from your fork to EvalAI.

Please feel free to ask if something is not clear.

**Comment by JaneLiuUSA** [comment]
Got it. Will do so. Thanks!
