### ISSUE TITLE
Add support for sorting leaderboard column wise

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1547]
## Current Scenario

One cannot sort the fields based on different columns in the leaderboard for a challenge.

## Deliverables

- [ ] Add support for sorting leaderboard based on different columns
- [ ] Make sure to add support for sorting based on the submission date. For example, see VQA 2017 Challenge leaderboard: https://evalai.cloudcv.org/web/challenges/challenge-page/1/leaderboard/
- [ ] Add proper comments in the codebase
- [ ] Write tests if possible to make sure that you are covering all the corner cases such as when the data is empty etc.

**Comment by xender98** [comment]
i will like to work on this issue..

**Comment by deshraj** [comment]
@xender98 sure, go ahead.

**Comment by vladan-jovicic** [comment]
Hi @deshraj and @xender98 

I almost finished this issue. The only remaining this is testing.
Here is a description of my approach:
- when user selects the challange phase, a new row is shown containing sort_by form
- the form contains names of labels of columns
- when an option is selected, the index of selected label is saved
- a corresponding url is defined, so that the index is an optional parameter in leaderboard view
- this is taken into account when sorted leaderboard data is constructed

The only remaining thing is testing. Currently, I am trying to insert some random results to see if everything works correctly. @xender98 do you want to help me with this?

**Comment by deshraj** [comment]
@vladan-jovicic: in future, please comment on an issue if you are interested in working on it. 

You can follow a different flow than creating a form as you have suggested above. See the table '2012 Gold Medal Olympic Divers' given in this link: http://www.bu.edu/tech/services/cccs/websites/www/wordpress/how-to/sortable-searchable-tables/

**Comment by xender98** [comment]
@deshraj so should i continue or move on another issue

**Comment by vladan-jovicic** [comment]
@deshraj I followed your suggestion and before I make a pull request, I would like to ask for a comment on styling.
Here are a few examples:

Without any sorting:
![0](https://user-images.githubusercontent.com/8584694/37244981-b222e960-2491-11e8-85c3-b8c6cd9193df.png)

Sort by "score" from largest to lowest
![1](https://user-images.githubusercontent.com/8584694/37244986-ccb4fc82-2491-11e8-9c45-908601947f7a.png)

Sort by "score2" from largest to lowest
![3](https://user-images.githubusercontent.com/8584694/37245032-87f03282-2492-11e8-8a20-13ea44177154.png)

There is an arrow next to column name indicating ascending or descending sort.

**Comment by deshraj** [comment]
@vladan-jovicic this looks good. You can create a pull request now. I will review it once you have created the pull request.

**Comment by deshraj** [comment]
@xender98: please pick some other issue.

**Comment by vladan-jovicic** [comment]
@deshraj I tried to make a PR. However, it fails travis checks. I don't see a reason since I changed only 2 files (challengeCtrl.js and leaderboard.html). Can you have a look and suggest how I can solve it?
