### ISSUE TITLE
UI Improvements in Leaderboard Entry

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1553]
- [ ] Show the meta data fields (**Team Members** and **Method Description**) in each leaderboard entry. 
Hint: Please refer the screenshot.
![6](https://user-images.githubusercontent.com/12206047/37241823-a1524bf0-2485-11e8-88a0-1b7c99ccfa9a.jpg)

- [ ] The user should be able to edit the **Method Description** field if the entry is created by the same user.

Please feel free to ask if you have doubts or queries.

**Comment by vladan-jovicic** [comment]
@RishabhJain2018 can I give a try to this one?

Is it ok if I add a details button to each leaderboard entry, so that when user clicks on it, a popup (see the image below) is shown containing the method description and other details about the method or I should add it next to the team name?

Example of popup
![00](https://user-images.githubusercontent.com/8584694/37298026-8a3ce664-261f-11e8-879e-0225d1f5dd7f.png)

**Comment by RishabhJain2018** [comment]
@vladan-jovicic I am sorry, I somehow missed this thread. Did you start working on it?

> s it ok if I add a details button to each leaderboard entry, so that when user clicks on it, a popup (see the image below) is shown containing the method description and other details about the method or I should add it next to the team name?

No, we don't need a button in leaderboard entry. It should be a collapsable as shown in the screenshot above.

**Comment by vladan-jovicic** [comment]
@RishabhJain2018 I have not started yet. I am struggling with another issue. I will come back to this one next week (if nobody solves it until then).

**Comment by RishabhJain2018** [comment]
@vladan-jovicic Okay!

**Comment by RishabhJain2018** [comment]
It seems like @vladan-jovicic has been inactive for a long time.
@live-wire Do you want to take this up ?

**Comment by deshraj** [comment]
@live-wire I am closing this issue here. Can you please open a similar issue for EvalAI-ngx? We should totally add this feature.
