### ISSUE TITLE
Unnecessary command to execute, listed in README for docker installation instructions 

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1698]
In README for docker installation, there is a command listed `cp settings/dev.sample.py settings/dev.py` but on inspection, it is found that there is no such file "settings/dev.sample.py" and it's throwing the following error:

![cp_command](https://user-images.githubusercontent.com/22341493/41037075-c65499e8-69af-11e8-98bf-8e5d56cfc6b9.png)

If this issue is valid can I work on this?
Thanks

**Comment by varunagrawal** [comment]
This seems to be an inconsistency in the README. We'll have to update that since when I wrote the docker instructions, we definitely had a sample dev settings file.
The last commit to have the sample dev settings is a1a93c192898fb1190d8dc11945e4fe70928967d so my recommendation would be to update the README and submit a PR :slightly_smiling_face:

**Comment by HargovindArora** [comment]
@varunagrawal Sure. I'm on it! :-)

**Comment by niranjani23** [comment]
Is this issue still open?

**Comment by varunagrawal** [comment]
I believe @HargovindArora has already submitted a PR. We'll close this issue once his PR is approved and merged.
