### ISSUE TITLE
Error in receiving message from submission queue with error 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1733]
https://sentry.io/cloudcv/evalai/issues/498341967/

```
Error in receiving message from submission queue with error 'NoneType' object has no attribute 'get'
```

Note that this error occurs whenever you try to make submission to a challenge which is not active/not approved. This leads to making the submission status stuck to `SUBMITTED` state only. Instead we would like to change it to canceled and show user a readable error message that 'Sorry your submission cannot be processed since the challenge is not active or is not approved by EvalAI Admin.'

**Comment by alrlchoa** [comment]
May I try fixing this bug?

**Comment by RishabhJain2018** [comment]
@alrlchoa Sure go ahead!

**Comment by alrlchoa** [comment]
Hi @RishabhJain2018 !
Thanks! Only got to see this now. While looking through the code, I had a couple of questions:

1) For the approval part of the admin, I opened up the Model for the Challenges. Correct me if I am wrong, but I did  not see any public function for calling approval property. Is that by design? If so, where may I get it? If not, may I create said public function or will something go wrong if I do (like security-wise or something)?

2) What should I  do with the job/submission when it gets disapproved? Should I dump it or let them keep it in front-end (like if the job is minutes away of going active)?

Thanks!

**Comment by sashank27** [comment]
@deshraj @RishabhJain2018 I would like to add this functionality. I am not very thorough with the codebase yet, so please guide me on how to proceed with this.

**Comment by nikhilmudholkar** [comment]
@deshraj @RishabhJain2018 I would like to work on this issue.

**Comment by RishabhJain2018** [comment]
Hi @nikhilmudholkar Sure, you can work on this issue.

**Comment by nikhilmudholkar** [comment]
Can someone help me with some basic pointers for solving this issue? The entire codebase to new to me.  At least, can anyone point me to relevant files and scripts where the issue needs to be solved?

**Comment by KhalidRmb** [comment]
@nikhilmudhokar Look at at the docs to get a basic understanding of the codebase: https://evalai.readthedocs.io/en/latest/ :)

**Comment by RishabhJain2018** [comment]
Hi @nikhilmudholkar For the first comment, please feel free to open a issue & fix it in a PR.

> Do we need to throw some sort of error when submitting to a challenge that is approved, is active but is not yet published?

No, we allow challenge hosts to keep the challenge private and make submissions to in order to test if everything is working fine or not.

**Comment by nikhilmudholkar** [comment]
@deshraj @RishabhJain2018 I have worked on this issue. I will PR shortly. I am sure that the travis CI build will fail. This is because of the following reason.
From a lot of testing and trying as you can see from the long list of commits above, I came to the conclusion that there is a small flaw when testing for this condition. I looked into the test_views of jobs file and found out that the approved_by_admin property of the challenge object is not set ( and the default value of which is FALSE). So when the tests for all other functions are run, the challenge object has approved_by_admin property as false. This won't give an error unless we write the condition for catching this problem(which is what I was trying to do precisely). Now when I wrote condition to deal with this problem, the tests failed because the challenge object in all the tests has this property as false. So the condition which I just wrote was executing instead of the ones that were supposed to be executed according to the tests. 
To indeed confirm this, I manually set (approved_by_admin=True) in the challenge object in the test_views. The Travis CI build was not failing now.
Can you guys please look into this and give suggestions?
Thanks a lot
