### ISSUE TITLE
Center align the leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2023]
## Current Behaviour

The leaderboard table metrics are not properly aligned with their header.

## Expected Behaviour

The header and values must be properly aligned.

## Deliverables

- [ ] Remove all the align classes like `align-right, align-left etc.` in the leaderboard.html
- [ ] Add a class `align-center` to `table` attribute in the same file.

## For Testing
- [ ] Create at least 5 entries on the leaderboard with different team names.
- [ ] Paste the screenshot with the entries along with the PR.

Please feel free to ask if there are any doubts.

**Comment by gautamjajoo** [comment]
Can I work on this?

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by deshraj** [comment]
@RishabhJain2018 I think you wrote the wrong class name here. The table should have a `centered` class instead of `align-center` so that it gets centered through materializecss. For reference, please see this https://materializecss.com/table.html. @gautamjajoo: please make sure that you don't miss this comment. :)

**Comment by gautamjajoo** [comment]
@deshraj @RishabhJain2018 This is screenshot when I use `centered` in `table` and `center` in `<tr>` tag. I have to use `center` in `<tr>` tag because without that the upper tab is not being center aligned. Is this okay? 

![](https://files.gitter.im/gautamjajoo/oUzK/Screenshot-from-2019-01-21-19-50-31.png)

**Comment by RishabhJain2018** [comment]
@gautamjajoo This looks good. Can you please open a PR for the same?

**Comment by ashish0910** [comment]
Can I take this issue ?

**Comment by RishabhJain2018** [comment]
Sorry, but this has already been taken.
