### ISSUE TITLE
Disable submissions from UI if the challenge is Docker based

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2090]
## Current Scenario

Currently, a user can submit to both docker based and non-docker based challenges using the UI. We'd like to restrict the user to submit to docker based challenges using the CLI.

## Expected Behaviour

The user can't submit to a challenge using the UI.

## Deliverables

- [ ] Add a check in the `challenge_submission` API to check if the challenge is docker based or not. If yes, then don't create a submission instead return a response saying `The challenge {} requires uploading code in the form of docker images. Please use EvalAI-CLI to make a submission.format(challenge.title)`. The response should be returned for both challenge host as well as participants.

- [ ] Add the test cases
- [ ] Add a check on UI using the field `is_docker_based` from the challenge model to disable all the form attributes in the submission page if `is_docker_based == true`.

Please feel free to ask in case of doubts.

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
sure!

**Comment by vkartik97** [comment]
@RishabhJain2018 
>Add a check on UI using the field `is_docker_based` from the challenge model to disable all the form attributes in the submission page if `is_docker_based == true`

Instead of Disabling Form, can I just Display `The challenge *title* requires uploading code in the form of docker images. Please use EvalAI-CLI to make a submission` below `Submission Guidelines`

Example:
![screenshot from 2019-02-09 03-04-15](https://user-images.githubusercontent.com/3920286/52507423-7c223f80-2c17-11e9-8e34-a37f76a89ccb.png)

**Comment by RishabhJain2018** [comment]
Yeah, this looks good to me!
