### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by amanex007** [Cloud-CV/EvalAI#2566]
A lot of files have duplicated code.
Files and counts are as follows.

Count | Path

1 | apps/base/utils.py
1)https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L16
   https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L157
1 | apps/challenges/views.py
1)https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L277
   https://github.com/Cloud-CV/EvalAI/blob/master/apps/participants/views.py#L230

Removing these duplicate codes and taking a look at them might help lessening the code and the unnecessary complexity.

**Comment by pushkalkatara** [comment]
@amanex007 please point the links too.

**Comment by amanex007** [comment]
sure

**Comment by amanex007** [comment]
done

**Comment by adrijshikhar** [comment]
@amanex007 is this issue still open?
i would like to work on this.

**Comment by Abhi58** [comment]
Hi @amanex007 . I have removed the duplicate strings 'domains' in the views.py of both participants and challenges folders. But, the base/utils.py duplicates mentioned in the issue can not be removed. Since, the code you mentioned is a library which is used to import PageNumberPagination module which is used in multiple places in the code. Also, in the #L157, do you want me to get rid of the entire method 'get_or_create_sqs_queue_object'. Please let me know. Thanks!

**Comment by amanex007** [comment]
Ask @pushkalkatara  to review it, he has opened this issue and has more knowleadge and understanding about the issue.

**Comment by Abhi58** [comment]
Sure @amanex007 . Thanks!!

**Comment by Abhi58** [comment]
@pushkalkatara Hi, could you please guide me through this?
