### ISSUE TITLE
Unordered list HTML tag <ul></ul> isn't getting rendered in evaluation details section

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2783]
**Description**:
In the evaluation details section if a challenge host wants to render a `<ul></ul>` tag then it isn't getting rendered properly.

**Comment by RishabhJain2018** [comment]
@Kajol-Kumari Can you please look into this?

**Comment by Kajol-Kumari** [comment]
sure @RishabhJain2018 sir.

**Comment by Kajol-Kumari** [comment]
@RishabhJain2018 @Sanji515 This issue is not only with `evaluation_detail_edit` but all the editing trix editors where angular-trix has been used i.e in `submission_guidelines_Edit`, `Terms_And_condition_Edit` etc. The trix-editor is working fine when i pasted it on plunker. So i thought maybe some .scss design is overwriting it. But even after removing all the styles from it. I am still just getting the blank space instead of bullet. Still can't figure out what is causing this problem. What am i missing?

**Comment by RishabhJain2018** [comment]
okay.
Did you check by inputting the `<ul></ul>` manually in the HTML of overview, etc? I think it also doesn't get rendered from there.

**Comment by Kajol-Kumari** [comment]
> okay.
> Did you check by inputting the `<ul></ul>` manually in the HTML of overview, etc? I think it also doesn't get rendered from there.

Yes i had tried this too. In this case also only blank space is appearing instead of bullets.

**Comment by RishabhJain2018** [comment]
I don't think you're missing anything and it is mostly the CSS override issue. Did you check in the console by removing the CSS to this `<ul></ul>` element?
