### ISSUE TITLE
Setup Throttling in drf backend

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#297]

**Comment by deshraj** [comment]
@RishabhJain2018 you showed interest in working on this. Are you still interested in working on this issue?

**Comment by RishabhJain2018** [comment]
@deshraj Yeah sure.

**Comment by RishabhJain2018** [comment]
@deshraj Please provide with some details and references on how to proceed with it.

**Comment by dexter1691** [comment]
@RishabhJain2018:
[This resource](http://www.django-rest-framework.org/api-guide/throttling/#example) seems to be a good starting point to setup throttling. 

The motivation to setup throttling is to prevent the server from being over-burdened by certain API calls that might be resource intensive. Like the submission related endpoints.  A concrete example might be that we want to throttle the number of submissions a user can make to a particular competition per minute? So that one user doesn't keep retrying if the submission is failing. 

@deshraj: What else? Can we list them here for easy reference. 

The leaderboard and all the other things that an unsigned viewer can see will probably not update a lot and will be cached. So might be okay to not throttle those, right?

**Comment by RishabhJain2018** [comment]
@dexter1691 Thank you for the resource.

yeah. It would be okay not to throttle the leaderboard. Moreover, I also want to ask about the throttling on login attempts, Do we also need to throttle that with a time limit ?

**Comment by RishabhJain2018** [comment]
@deshraj @dexter1691 I also found a open source load testing tool http://locust.io/ . Please have a look. May be it would help us in some way.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this issue now?

**Comment by deshraj** [comment]
Yup.
