### ISSUE TITLE
[FrontendV2] Fix private split tag css on the leaderboard

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3158]
### Description

`Private` tag for a challenge phase split should appear next to the phase split name in the dropdown on the `Leaderboard` tab of the challenge page. Because of inconsistent css the `private` tag for a challenge phase split is aligned below the phase split text in dropdown.

Here's a screenshot for reference

<img width="1440" alt="Screen Shot 2021-01-20 at 9 47 11 PM" src="https://user-images.githubusercontent.com/16323427/105203684-6a6aa600-5b69-11eb-8b20-f0c6d91f79fe.png">

**Comment by Devanshu24** [comment]
Hi @Ram81 !
I would like to give it a shot, if it is okay with you and if no one else is already working on it :)

**Comment by Devanshu24** [comment]
After playing with the code a little I think that `frontend` is the default one that is being used, could you guide me on how to use `frontendV2`.

**Comment by Ram81** [comment]
@Devanshu24 sure, go ahead.

>After playing with the code a little I think that frontend is the default one that is being used, could you guide me on how to use frontendV2.

You can access it on `localhost:4200`  port.

**Comment by Devanshu24** [comment]
![Screenshot from 2021-01-21 15-34-20](https://user-images.githubusercontent.com/56106207/105335576-368d9000-5bfe-11eb-87d8-3cbce5ce2585.png)



This is not exactly the issue you had pointed out, but when I was on the leaderboard page I could see that phase selector was sort of bumping into the Precision Value selector (the image is a little small, so please open it in a new tab), this is to my understanding because of the following lines
https://github.com/Cloud-CV/EvalAI/blob/c4899ac9f5916e72d5ddb4e01b48ffbe35e80d16/frontend_v2/src/styles/base.scss#L215-L219
I did not understand the reason for that specific value (`478px`)

I could override the `width` property in the component's scss file here (by setting the `ViewEncapsulation` to `None` more info [here](https://angular.io/api/core/ViewEncapsulation) )
https://github.com/Cloud-CV/EvalAI/blob/c4899ac9f5916e72d5ddb4e01b48ffbe35e80d16/frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.scss#L169-L171

First I wanted to run the idea by you once :)

**Comment by Ram81** [comment]
Fixed in #3225

@Devanshu24  the issue of dropdown overlaying on precision value is fixed in #3225.
