### ISSUE TITLE
Change `created_by` field from integer to username in `api/hosts/challenge_host_team/` API endpoint

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#324]

**Comment by gauthamzz** [comment]
can i try?

**Comment by deshraj** [comment]
Sure. Go ahead.

**Comment by deshraj** [comment]
@gauthamzz are you working on it? If yes, can you please do it quicker since we need to fix it soon.

**Comment by gauthamzz** [comment]
@deshraj I'm trying but something is wrong with testing it . cos of proxy . ill try to do it fast

**Comment by deshraj** [comment]
Oh wait, I know this error. We recently integrated memcache backend with the codebase so you hace to include those settings. Please re-copy the dev.sample.py to dev.py since there are new changes in there.

**Comment by gauthamzz** [comment]
Its working now . Can you give me a hint how to solve this ?

**Comment by deshraj** [comment]
Can you tell me that what was the issue?

**Comment by gauthamzz** [comment]
the created by field was returning user id instead of username

**Comment by gauthamzz** [comment]
the created by field was returning user id instead of username @deshraj .
{"count":5,"next":null,"previous":null,"results":[{"id":1,"team_name":"Gautham","created_by":1},{"id":4,"team_name":"gfffff","created_by":1},{"id":5,"team_name":"dhggggggggg","created_by":1},{"id":6,"team_name":"sssssssssssssssss","created_by":1},{"id":7,"team_name":"adssssssssssss","created_by":1}]}%

needed to be changed to

{"count":5,"next":null,"previous":null,"results":[{"id":1,"team_name":"Gautham","created_by":"gautham"},{"id":4,"team_name":"gfffff","created_by":"gautham"},{"id":5,"team_name":"dhggggggggg","created_by":"gautham"},{"id":6,"team_name":"sssssssssssssssss","created_by":"gautham"},{"id":7,"team_name":"adssssssssssss","created_by":"gautham"}]}%

**Comment by gauthamzz** [comment]
This was how it was supposed to look 

'default': {
'ENGINE': 'django.db.backends.postgresql_psycopg2',
'NAME': 'evalai',
'USER': 'your username',
'PASSWORD': 'your password',
'HOST': 'localhost',
'PORT': '5432',
}

but the field password is not there and field NAME is not equal to EVALAI @deshraj

**Comment by gauthamzz** [comment]
close this ?

**Comment by deshraj** [comment]
Thanks @gauthamzz  :-)
