### ISSUE TITLE
[Frontend V2] Fix the media assets endpoint

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3345]
### Description

We recently moved to `https://evalai.s3.amazonaws.com/` endpoint for our media assets. Frontend v2 is still using `https://staging-evalai.s3.amazonaws.com/` endpoint. We should switch to new enpdoint in frontend v2.

**Comment by gautamjajoo** [comment]
Can I work on it? @Ram81

**Comment by Ram81** [comment]
@gautamjajoo sure, go ahead

**Comment by niharsalunke** [comment]
Hi @Ram81, I am sorry to bring this up now. It seems the media URL on the staging website is wrongly set. This cannot be fixed with our local machines. 

To be specific, the "AWS_STORAGE_BUCKET_NAME" environment variable present on the **STAGING_MACHINE/EvalAI/docker/prod/docker_staging.env** needs to be changed from **"staging-evalai"** to **"evalai"**. Since these environment variables are currently hidden from the contributors, there is very little we can do here. Please let me know if I am missing something here.
Thanks.
