### ISSUE TITLE
Replication of Google Analytics code.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#763]
Google analytics code is used in index as well as in base. @spyshiv I think only base can work. Thoughts?

**Comment by spyshiv** [comment]
@aka-jain : This is not a replica since base file is not being served anywhere. When `gulp inject` run then path of static files are injected into `base.html` and then it duplicated as `index.html` . So basically `index.html` is formed using `base.html`.
PS: `index.html` is in `.gitignore` also.

Let me know if you wanted to say something else.
